name: CI Lint and Tests

# Controls when the action will run. Triggers the workflow on pull request
# events or push events in the develop branch.
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:    
      # Push events on develop branch
      - develop

# This workflow has the following jobs:
# linters: Kotlin and Protobuf Linting
# robolectric_tests: Robolectric tests for all modules except the app module
# app_tests: Non-flaky Robolectric tests for the app module
jobs:
  app_emulator_tests:
    name: Espresso Emulator Tests - App Module (Non-Flaky)
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [default]
        profile: [Nexus 6]
        #profile: [Pixel XL]
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
         path: ~/.gradle/caches
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-jars-{{ checksum "build.gradle" }}
         
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9

      - name: Set up Android SDK tools
        uses: android-actions/setup-android@v2.0.1

      - name: Run emulator tests
        uses: ReactiveCircus/android-emulator-runner@v2.11.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          profile: ${{ matrix.profile }}
          arch: x86_64
          # For reference: https://stackoverflow.com/a/42518783.
          script: sudo scripts/run_emulator_tests.sh
          #script: sudo ./gradlew :app:connectedDevAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=org.oppia.app.splash.SplashActivityTest

      
